# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Numerically stable log(sum(exp(x)))
#' @param x arma::vector
#' @return scalar giving log(sum(exp(x)))
#' @name logsumexp
#' @noRd
NULL

#'Categorical sampler
#' @param log probabilities for categorical distribution
#' @return integer giving a random draw from a categorical distribution
#' @name rcat
#' @noRd
NULL

#' stick breaking weights from stick breaking variables
#' @param x:   K-1 dim arma::vec of stick-breaking [Beta(1, alpha)] variables
#' @param log: if true, returns result on log scale
#' 
#' @return K dim arma::vec of log of stick breaking weights
#' @noRd
NULL

#' Truncated gamma random variable generation
#' 
#' Generates truncated gamma random variates via the inverse-CDF method
#' 
#' @param shape shape parameter for gamma distribution
#' @param rate rate parameter for gamma distribution
#' @param a lower truncation point (non-negative integer)
#' @param b upper truncation point (non-negative integer; b > a)
#' @return single draw from truncated gamma distribution
#' @noRd
NULL

#' Generate from Dirichlet(1, ..., 1)
#' @param n number of parameters
#' @param log whehter to return result on log scale
#' 
#' @return Dirichlet(1, ..., 1) vector on specified scale
#' @noRd 
NULL

#' Compute marginal survival function based on DPMM regression
#'
#' @param Mu nxK matrix giving mean of each observation for each class
#' @param sigma K-dim vector giving standard deviation for each class
#' @param logw K-dim vector giving log weight for each class
#' @param logomega n-dim vector giving log of Dirichlet random variable
#' @param logtimes T-dim vector specifying where to report the survival function
#' @param log if true, reports log survival function
#'
#' @return T-dim vector giving marginal survival function on specified scale
#' @noRd
NULL

#' Compute conditional RMST function based on DPMM regression
#'
#' @param Mu nxK matrix giving mean of each observation for each class
#' @param sigma K-dim vector giving standard deviation for each class
#' @param logw K-dim vector giving log weight for each class
#' @param logtimes T-dim vector specifying which logtimes to evaluate the RMST
#'
#' @return T x n matrix of log RMST values
#' @noRd
NULL

#' Compute marginal RMST function based on DPMM regression
#'
#' @param Mu nxK matrix giving mean of each observation for each class
#' @param sigma K-dim vector giving standard deviation for each class
#' @param logw K-dim vector giving log weight for each class
#' @param logomega n-dim vector giving log of Dirichlet random variable
#' @param logtimes T-dim vector specifying which logtimes to evaluate the RMST
#' @param log if true, reports log RMST
#'
#' @return T-dim vector giving marginal RMST on specified scale
#' @noRd
NULL

#' Compute conditional hazard function based on DPMM regression
#' 
#' @param Mu nxK matrix giving mean of each observation for each class
#' @param sigma K-dim vector giving standard deviation for each class
#' @param logw K-dim vector giving log weight for each class
#' @param logtimes T-dim vector specifying which logtimes to evaluate the hazard
#'
#' @return T x n matrix of log hazard values
#' @noRd
NULL

#' Compute marginal hazard function based on DPMM regression
#'
#' @param Mu nxK matrix giving mean of each observation for each class
#' @param sigma K-dim vector giving standard deviation for each class
#' @param logw K-dim vector giving log weight for each class
#' @param logomega n-dim vector giving log of Dirichlet random variable
#' @param logtimes T-dim vector specifying which logtimes to evaluate the hazard
#' @param log if true, reports log hazard
#'
#' @return T-dim vector giving marginal hazard function on specified scale
#' @noRd
NULL

#' Convert Rcpp list of historical data to a tteHistData object
#' @keywords internal
#' @noRd
NULL

#' Sample from truncated beta distribution
#' @keywords internal
#' @noRd
#' @export
NULL

#' Numerically stable log(exp(logb) - exp(loga))
#' @param logb larger logged number
#' @param loga smaller logged number
#' @noRd
NULL

sample_tbeta_mixture_posterior <- function(shape1, shape2, lower, upper, prior_prob, nexch, nunexch) {
    .Call(`_bnpdb_sample_tbeta_mixture_posterior`, shape1, shape2, lower, upper, prior_prob, nexch, nunexch)
}

#' C++ sampler of BNPDB method for time-to-event data
#' 
#' @param data_list a `list` with the elements (y, event, X)c orresponding to the current data
#' @param histdata_list a `list` with the elements (y, event, X) corresponding to the external data
#' @param basemeasure_list a `list` giving the base measure and priors
#' @param inits_list a `list` giving initial values
#' @param niter number of MCMC samples post burn-in and thinning
#' @param nburnin burn-in size
#' @param nthin thin size
#' 
#' @return a list giving posterior samples
#' @keywords internal
#' @noRd
tte_reg_bnpdb_cpp <- function(data_list, histdata_list, basemeasure_list, inits_list, niter, nburnin, nthin) {
    .Call(`_bnpdb_tte_reg_bnpdb_cpp`, data_list, histdata_list, basemeasure_list, inits_list, niter, nburnin, nthin)
}

#' C++ sampler of DPMM method for time-to-event data
#' 
#' @param niter number of desired posterior samples post burn-in
#' @param nburnin number of burn-in samples
#' @param thin number of samples to thin post burn-in
#' 
#' @return a list giving posterior samples
#' @noRd
tte_reg_dpmm_cpp <- function(data_list, basemeasure_list, inits_list, niter, nburnin, nthin) {
    .Call(`_bnpdb_tte_reg_dpmm_cpp`, data_list, basemeasure_list, inits_list, niter, nburnin, nthin)
}

#' Obtain marginal quantities when design matrix consists only of strata.
#' 
#' 
#' @param X design matrix with S rows and S columns, S = number of strata.
#' @param samples a named `list` giving posterior samples of the DPMM
#' @param log_survival_times log of times to evaluate survival function
#' @param log_survival boolean; if true: outputs log of survival function
#' @param log_hazard_times log of time points to evaluate hazard function
#' @param log_hazard boolean; if true: outputs log of hazard function
#' @param log_rmst_times log of times to evaluate RMST function
#' @param log_rmst boolean; if true: outputs log of RMST function
#' @keywords internal
#' @noRd
marginalize_strataonly <- function(X, samples, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst) {
    .Call(`_bnpdb_marginalize_strataonly`, X, samples, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst)
}

#' Marginalize over strata for time-to-event regression using posterior samples
#'
#' @param Xlist a list of S design matrices (one per stratum), each with n rows
#' @param samples_list a list of length S, each element a named list of posterior samples (`beta`, `sigma`, `w`)
#' @param log_survival_times log of times to evaluate survival function
#' @param log_survival boolean; if true: outputs log of survival function
#' @param log_hazard_times log of time points to evaluate hazard function
#' @param log_hazard boolean; if true: outputs log of hazard function
#' @param log_rmst_times log of times to evaluate RMST function
#' @param log_rmst boolean; if true: outputs log of RMST function
#'
#' @return a named list of three 3D arrays (`survival`, `rmst`, `hazard`) with dimensions (time × MCMC × S)
#' @keywords internal
#' @noRd
marginalize_tte_gcomp <- function(Xlist, samples_list, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst) {
    .Call(`_bnpdb_marginalize_tte_gcomp`, Xlist, samples_list, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst)
}

