# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ sampler of BNPDB method for time-to-event data
#' 
#' @param data_list a `list` with the elements (y, event, X)c orresponding to the current data
#' @param histdata_list a `list` with the elements (y, event, X) corresponding to the external data
#' @param basemeasure_list a `list` giving the base measure and priors
#' @param inits_list a `list` giving initial values
#' @param niter number of MCMC samples post burn-in and thinning
#' @param nburnin burn-in size
#' @param nthin thin size
#' 
#' @return a list giving posterior samples
#' @keywords internal
#' @noRd
tte_reg_bnpdb_cpp <- function(data_list, histdata_list, basemeasure_list, inits_list, niter, nburnin, nthin) {
    .Call(`_bnpdb_tte_reg_bnpdb_cpp`, data_list, histdata_list, basemeasure_list, inits_list, niter, nburnin, nthin)
}

#' C++ sampler of DPMM method for time-to-event data
#' 
#' @param niter number of desired posterior samples post burn-in
#' @param nburnin number of burn-in samples
#' @param thin number of samples to thin post burn-in
#' 
#' @return a list giving posterior samples
#' @noRd
tte_reg_dpmm_cpp <- function(data_list, basemeasure_list, inits_list, niter, nburnin, nthin) {
    .Call(`_bnpdb_tte_reg_dpmm_cpp`, data_list, basemeasure_list, inits_list, niter, nburnin, nthin)
}

#' Obtain marginal quantities when design matrix consists only of strata.
#' 
#' 
#' @param X design matrix with S rows and S columns, S = number of strata.
#' @param samples a named `list` giving posterior samples of the DPMM
#' @param log_survival_times log of times to evaluate survival function
#' @param log_survival boolean; if true: outputs log of survival function
#' @param log_hazard_times log of time points to evaluate hazard function
#' @param log_hazard boolean; if true: outputs log of hazard function
#' @param log_rmst_times log of times to evaluate RMST function
#' @param log_rmst boolean; if true: outputs log of RMST function
#' @keywords internal
#' @noRd
marginalize_strataonly <- function(X, samples, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst) {
    .Call(`_bnpdb_marginalize_strataonly`, X, samples, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst)
}

#' Marginalize over strata for time-to-event regression using posterior samples
#'
#' @param Xlist a list of S design matrices (one per stratum), each with n rows
#' @param samples_list a list of length S, each element a named list of posterior samples (`beta`, `sigma`, `w`)
#' @param log_survival_times log of times to evaluate survival function
#' @param log_survival boolean; if true: outputs log of survival function
#' @param log_hazard_times log of time points to evaluate hazard function
#' @param log_hazard boolean; if true: outputs log of hazard function
#' @param log_rmst_times log of times to evaluate RMST function
#' @param log_rmst boolean; if true: outputs log of RMST function
#'
#' @return a named list of three 3D arrays (`survival`, `rmst`, `hazard`) with dimensions (time × MCMC × S)
#' @keywords internal
#' @noRd
marginalize_tte_gcomp <- function(Xlist, samples_list, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst) {
    .Call(`_bnpdb_marginalize_tte_gcomp`, Xlist, samples_list, log_survival_times, log_survival, log_hazard_times, log_hazard, log_rmst_times, log_rmst)
}

